### ISSUE TITLE
Install cross-env to support windows developers

### ISSUE THREAD

**Issue by epicseven-cup** [UBAutograding/devU-client#2]
When installing the node packages one issue I ran across was it fails to install node-sass here's the error output:

> C:\Users\idkmyname\IdeaProjects\devU-client>npm install

>npm WARN deprecated har-validator@5.1.5: this library is no longer supported
>npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain >circumstances, which is known
>to be problematic.  See https://v8.dev/blog/math-random for details.
>npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
>npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
>npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
>npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less >dependencies.
>npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less >dependencies.
>npm ERR! code 1
>npm ERR! path C:\Users\idkmyname\IdeaProjects\devU-client\node_modules\node-sass
>npm ERR! command failed
>npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
>npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\idkmyname\IdeaProjects\devU-client\node_modules\node->gyp\bin\node-gyp.js rebuild --verbose --l
>ibsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
>npm ERR! gyp info it worked if it ends with ok
>npm ERR! gyp verb cli [
>npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
>npm ERR! gyp verb cli   'C:\\Users\\idkmyname\\IdeaProjects\\devU-client\\node_modules\\node-gyp\\bin\\node-gyp.js',
>npm ERR! gyp verb cli   'rebuild',
>npm ERR! gyp verb cli   '--verbose',
>npm ERR! gyp verb cli   '--libsass_ext=',
>npm ERR! gyp verb cli   '--libsass_cflags=',
>npm ERR! gyp verb cli   '--libsass_ldflags=',
>npm ERR! gyp verb cli   '--libsass_library='
>npm ERR! gyp verb cli ]
>npm ERR! gyp info using node-gyp@3.8.0
>npm ERR! gyp info using node@16.2.0 | win32 | x64
>npm ERR! gyp verb command rebuild []
>npm ERR! gyp verb command clean []
>npm ERR! gyp verb clean removing "build" directory
>npm ERR! gyp verb command configure []
>npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
>npm ERR! gyp verb `which` failed Error: not found: python2
>npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\idkmyname\IdeaProjects\devU-`

I think the node-gyp is looking for python 2 because of the version of node-sass we are using (guessing).
This are the info I found online:
       [Node.js: Python not found exception due to node-sass and node-gyp](https://stackoverflow.com/questions/45801457/node-js-python-not-found-exception-due-to-node-sass-and-node-gyp)

Another issue I have is:
>npm start

> start
> NODE_ENV=development webpack-dev-server -d --open --mode development

>'NODE_ENV' is not recognized as an internal or external command,
>operable program or batch file.

I think this might be because since I'm trying to run it on the window which the command is different from the Unix command

[“NODE_ENV” is not recognized as an internal or external command, operable command or batch file](https://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman)

This was fix by using laggingreflex's answer on that StackOverflow question. Which is just install another node package that converts the commands

[Link to the node package](https://github.com/laggingreflex/win-node-env)

**Comment by MikeDrewitt** [comment]
`node-sass` will be removed in the project in [this PR](https://github.com/UBAutograding/devU-client/pulls). Give that branch a try and see if you have better luck.

**Comment by MikeDrewitt** [comment]
Keep in mind that with that branch the site will hang at a nearly blank starting page because it's requiring auth. But npm install should work fine.

**Comment by beetosu** [comment]
It looks like the issue is still persisting on Windows. I was able to fix it by manually changing the scripts in package.json (for example, I changed `"local": "NODE_ENV=local webpack-dev-server -d --open --mode development"` to `"local": "SET NODE_ENV=local && webpack-dev-server -d --open --mode development"`)

**Comment by MikeDrewitt** [comment]
Ah I see. Either I was misunderstanding your previous comment, or that one was fixed and this is a separate issue. 

Either way, we'll reopen this issue because we have a solution. We're going to have to install [cross-env](https://www.npmjs.com/package/cross-env) and get those scripts in the package json using that so that devs can use both windows and unix systems. 

@beetosu do you want to take this? Should be a fairly easy piece of low hanging fruit.

If you want to take this, assign yourself this issue and put up a PR for it. Otherwise I'll fix this in the next few days or so.

**Comment by beetosu** [comment]
Sounds good, I'll get working on it!
I don't believe I have permission to assign myself the issue, however.

**Comment by MikeDrewitt** [comment]
Bam 💪  looking forward to the PR.
