### ISSUE TITLE
userCoursesListPage not creating UserCourseListItems

### ISSUE THREAD

**Issue by beetosu** [UBAutograding/devU-client#38]
### Subject of the issue
-------------------------------------------
For testing purposes, I created a user, course, and a user_courses model within my local database. I then went to access the `user/:userId/courses` page. The exact models as shown in the network in the logs below.

### Expected behaviour
-------------------------------------------
Using these models, the page should generate UserCourseListItems and display them like the images provided in the [My Courses PR](https://github.com/UBAutograding/devU-client/pull/34).

### Actual behaviour
-------------------------------------------
The page produces an entirely blank page, with the following error being displayed:
![courseIsUndefined](https://user-images.githubusercontent.com/29612529/128372944-c74468eb-5647-468d-a7a0-9e8cbd9840a9.PNG)

### Steps to reproduce
-------------------------------------------
I believe that this error could be reproduced by creating a user with one userCourse object, with the userCourse id being different than the Course id.

I was able to resolve this issue by modifying the generation of UserCourseListItem in line 88 of userCoursesListPage.tsx from this:
```js
<UserCourseListItem key={userCourse.courseId} userCourse={userCourse} course={courses[userCourse.id || '']} />
```

to this
```js
<UserCourseListItem key={userCourse.courseId} userCourse={userCourse} course={courses[userCourse.courseId]} />
```

This leads me to believe the problem lies with how the `courses` record is used. Looking at the comments, it seems to be intended to map a course's Id with the course object, but in the original UserCourseListItem generation is called using the userCourse object's id. In the case of my objects these are two entirely different ids, so `courses[userCourse.id || '']` returns undefined, causing the error.

### Any relevant logs, error output, etc?
-------------------------------------------
For reference, these are the objects being used, as they appear in the network:

My User:
```
{"id":1,"externalId":"cpwalsh","email":"cpwalsh@buffalo.edu","createdAt":"2021-08-04T21:26:08.560Z","updatedAt":"2021-08-04T21:26:08.560Z","preferredName":null}
```

My Course:
```
{"id":5,"name":"Advanced FORTRAN","semester":"Fall 2021","number":"123","startDate":"2021-08-04T04:00:00.000Z","endDate":"2021-12-01T05:00:00.000Z","createdAt":"2021-08-05T18:03:14.116Z","updatedAt":"2021-08-05T18:03:14.116Z"}
```

My userCourse:
```
[{"id":1,"userId":1,"courseId":5,"level":"student","dropped":false,"createdAt":"2021-08-05T18:12:31.620Z","updatedAt":"2021-08-05T18:12:31.620Z"}]
```

**Comment by MikeDrewitt** [comment]
Good catch
