### ISSUE TITLE
Toggleable list component

### ISSUE THREAD

**Issue by MikeDrewitt** [UBAutograding/devU-client#6]
### Feature request
------------------------
Toggleable list component that matches these 

![image](https://user-images.githubusercontent.com/10001042/121978564-76dcde80-cd56-11eb-8924-f677420c2fc1.png)

Props look like this

```
type Options = {
  label: string,
  onClick: () => void,
}

type Props = {
  title: string
  options: Options[],
  defaultOpen: boolean,
}
```

- [ ] Fancy open and close animation

**Comment by MikeDrewitt** [comment]
If you're not too far into this @Searay-330 we might want to just drop this since we're not 1:1 recreating the existing site anymore.

**Comment by Searay-330** [comment]
yeah i didnt really do much given the environment issues i had only really did enough to knock the dust off lets close this one out
